### ISSUE TITLE
moleculer config with sealed objects

### ISSUE THREAD

**Issue by elixiao** [moleculerjs/moleculer#710] opened 2020-04-02 04:42 UTC
I use moleculer with node-config. App crashes immediately after running without any message. After hours of research, I found maybe the reason is config object is sealed and immutable but moleculer wants to modify it. If moleculer failed to start, why not print some error messages?

```js
const config = require('config')
const {ServiceBroker} = require('moleculer')
const broker = new ServiceBroker(config.get('moleculer'))
broker.start()
  .then(() => {
    console.log('moleculer broker success!')
  })
  .catch((e: any) => {
    console.log('moleculer broker failed!')
  })
```

**Comment by AndreMaz** [comment] 2020-04-02 05:18
From [FAQ](https://moleculer.services/docs/0.14/faq.html#Why-the-broker-exits-without-any-error-when-I-start-my-service): _If there is no continuously running process (e.g., transporter connection, API gateway, DB connection) that keeps event loop running then the process will exit. It’s normal behavior and not a bug. If you want to keep your service broker running then you should keep the event loop “busy”. Try to enable the transporter in moleculer.config.js._

**Comment by elixiao** [comment] 2020-04-02 07:25
@AndreMaz There is  transporter connection in `moleculer.config.js`. The problem is if transporter.options is sealed, Moleculer exits without error message. You can try the following BrokerOptions:

```js
{
  namespace: 'test',
  logLevel: 'warn',
  transporter: {
    type: 'NATS',
    options: Object.seal({
      url: 'nats://nats:4222',
      maxReconnectAttempts: 10
    })
  }
}
```

**Comment by AndreMaz** [comment] 2020-04-02 10:21
Hey @elixiao 

Tested over here with your snipped and I got a `Unable to create ServiceBroker` error that is present in ServiceBroker constructor.

![image](https://user-images.githubusercontent.com/9802754/78237694-92522580-74d3-11ea-99e0-6a8fc672dd60.png)

**Comment by AndreMaz** [comment] 2020-04-02 10:37
As a workaround you can use lodash `cloneDeep` function to "unseal" the config. object right before passing it to the constructor. This way the ServiceBroker can modify it as needed.

**Comment by elixiao** [comment] 2020-04-03 08:26
@AndreMaz Thanks. Add `logger:true` to BrokerOptions could show error messages now. Because `config.get('xxx')` results a deep sealed object. If I don't add `logger: true`, the app just exits without any output.

```js
const {ServiceBroker} = require('moleculer')

const options = Object.seal({
  namespace: 'test',
  logLevel: 'warn',
  logger: true, // <---- here is the key point, if remove this line, there are no error messages and app just exists
  transporter: Object.seal({
    type: 'NATS',
    options: Object.seal({
      url: 'nats://localhost:4222',
      maxReconnectAttempts: 10
    })
  })
})

const broker = new ServiceBroker(options)

broker.start()
  .then(() => {
    console.log('moleculer broker success!')
  })
  .catch((e) => {
    console.log('moleculer broker failed!')
  })
```

**Comment by icebob** [comment] 2020-04-04 08:14
@elixiao what is your use-case why you are using sealed objects?

**Comment by elixiao** [comment] 2020-04-05 05:07
@icebob Actually I don't want to use sealed objects. However, [node-config](https://github.com/lorenwest/node-config) returns me a sealed object. I put moleculer BrokerOptions into default.json/production.json in order to connect to different transporter. node-config loads different json file according to different NODE_ENV. 

![image](https://user-images.githubusercontent.com/2291033/78467330-26bfc080-773e-11ea-8af3-94bd7888a04d.png)

```js
const config = require('config')
const {ServiceBroker} = require('moleculer')
const brokerOptions = config.get('moleculer')
const broker = new ServiceBroker(brokerOptions)
```

**Comment by icebob** [comment] 2020-04-05 08:29
Please create a repro repo and I will check what we can do to solve it.

**Comment by elixiao** [comment] 2020-04-05 13:05
@icebob https://github.com/elixiao/moleculer-demo
use `node src/` or `npm run dev` to run demo.

**Comment by icebob** [comment] 2023-01-14 13:05
I'm closing this issue, because we don't know, how we can solve it inside Moleculer. If you have idea or solution please reopen or open a PR.

**Closed by icebob** 2023-01-14 13:05 UTC
Labels: Priority: Low, help wanted, Module: Core
