### ISSUE TITLE
Misleading event architecure which violate separation of concerns

### ISSUE THREAD

**Issue by wiiiteek** [moleculerjs/moleculer#917] opened 2021-04-24 09:29 UTC
Hi,

For the last two weeks I'm moving my CRM system to moleculer. And for now I think moleculer is really cool, but today I've encountered some problem. I'm not sure, but I believe that the event/broadcast concept is wrong in terms of separations of concerns. 

Events in microservices should not be aware of other services which receive it. Emitters shouldn't care if an event will be received only by one instance (balanced event) or by all instances (broadcast event) - emitter just saying "Hi guys I don't know if anybody cares but I just `event.code`". In the other service which is interested in receiving event we should be able to declare if we want to handle given event in all service instances or in only one instance

For example, let's say we have `MessagesService` which emits the event `message.created` after the message was created. We also have a second service `NotificationsService` which creates user notifications in DB based on different events. `NotificationsService` wants to handle events **only in one** instance, because in the other case every instance would create own DB entry for the same event

But let's say we also have `WSPushService` which is a WebSocket push notificator. In opposite to `NotificationsService` this one wants to handle events **in all instances** to properly sends information to all connected users.

With present approach handling this case is not possible. Of course we can send two different events such as:

```js
// MessagesService.js

ctx.emit("message.created", {message: msg});  // for NotificationsService
ctx.broadcast("b.messages.created", {message: msg}); // for WSPushService
```
But now we are tightly coupling all services which violate separation rules.

**What I'm proposing is**:

Let's move handling strategy responsibility from the emitter to receiver by adding in event subscription config new property, eg `handleStrategy`:

```js
// notifications.service.js
module.exports = {
    name: "notifications",
    events: {
        "message.created": {
            handleStrategy: "one", // <---  or "all"
            params: {
                message: "object"
            },
            handler(ctx) {
                this.logger.info("Event received only in ONE instance");
            }
        }
    }
};
```

I will try to check moleculer source and make my own changes, but let me know what you think about it?

**Comment by ngraef** [comment] 2021-04-26 06:01
Good example and proposal. This looks like a duplicate of https://github.com/moleculerjs/moleculer/issues/792. If you agree, let's continue the conversation over there.

**Comment by wiiiteek** [comment] 2021-04-26 07:06
@ngraef Ahh, sorry I didn't see that you already described that problem earlier. Yes, sure - let's move it to #792

**Closed** 2021-04-27 19:36 UTC
