### ISSUE TITLE
Can you change 'HEARTBEAT' log level from 'debug' to 'trace' ?

### ISSUE THREAD

**Issue by roytan883** [moleculerjs/moleculer#321] opened 2018-07-10 03:38 UTC
The `HEARTBEAT` logs always flush `debug` logs, can you move it to `trace` or anywhere i can disable `HEARTBEAT` logs ?

```
18-07-10_11:31:14.282 DEBUG transit: Incoming EVENT packet from 'rts-auth-dev-88-0'
18-07-10_11:31:14.286 DEBUG transit: Event 'metrics.trace.span.finish' received from 'rts-auth-dev-88-0' node in 'metrics' group(s).
18-07-10_11:31:14.287 DEBUG transit: Incoming EVENT packet from 'rts-demo-dev-88-1'
18-07-10_11:31:14.288 DEBUG transit: Event 'metrics.trace.span.finish' received from 'rts-demo-dev-88-1' node in 'metrics' group(s).
18-07-10_11:31:14.289 DEBUG transit: Incoming EVENT packet from 'rts-demo-dev-88-1'
18-07-10_11:31:14.290 DEBUG transit: Event 'metrics.trace.span.finish' received from 'rts-demo-dev-88-1' node in 'metrics' group(s).
18-07-10_11:31:14.290 DEBUG transit: Incoming EVENT packet from 'rts-apiGateway-dev-88-0'
18-07-10_11:31:14.290 DEBUG transit: Event 'metrics.trace.span.finish' received from 'rts-apiGateway-dev-88-0' node in 'metrics' group(s).
18-07-10_11:31:14.504 DEBUG transit: Incoming HEARTBEAT packet from 'rts-apiGateway-dev-88-0'
18-07-10_11:31:14.706 DEBUG transit: Incoming HEARTBEAT packet from 'rts-demo-dev-88-0'
18-07-10_11:31:15.102 DEBUG metrics: Span sending error! Cannot decode spans [object Object],[object Object],[object Object],[object Object]
18-07-10_11:31:17.129 DEBUG transit: Incoming HEARTBEAT packet from 'rts-auth-dev-88-0'
18-07-10_11:31:17.288 DEBUG transit: Send HEARTBEAT packet to '<all nodes>'
18-07-10_11:31:17.559 DEBUG transit: Incoming HEARTBEAT packet from 'rts-demo-dev-88-1'
18-07-10_11:31:19.505 DEBUG transit: Incoming HEARTBEAT packet from 'rts-apiGateway-dev-88-0'
18-07-10_11:31:19.706 DEBUG transit: Incoming HEARTBEAT packet from 'rts-demo-dev-88-0'
18-07-10_11:31:22.131 DEBUG transit: Incoming HEARTBEAT packet from 'rts-auth-dev-88-0'
18-07-10_11:31:22.290 DEBUG transit: Send HEARTBEAT packet to '<all nodes>'
18-07-10_11:31:22.559 DEBUG transit: Incoming HEARTBEAT packet from 'rts-demo-dev-88-1'
18-07-10_11:31:24.506 DEBUG transit: Incoming HEARTBEAT packet from 'rts-apiGateway-dev-88-0'
18-07-10_11:31:24.707 DEBUG transit: Incoming HEARTBEAT packet from 'rts-demo-dev-88-0'
```

BTW, seems `moleculer-zipkin` has something wrong with latest zipkin, i'm looking into it

**Comment by icebob** [comment] 2018-07-10 20:43
Good idea, could you make a PR?

**Comment by WoLfulus** [comment] 2018-08-04 18:37
Maybe all packets should be moved to trace instead of debug? It's network level.

**Comment by icebob** [comment] 2018-08-04 18:51
good idea. Could you make a PR?

**Comment by icebob** [comment] 2018-08-04 19:04
Although, it can' solve the original issue, that if you want to see the transferred packets, the many HEARTBEAT packets make a noise. If we move all messages to TRACE, no changes. But, if you want to debug your services and not transporter, you can fine tuning the level since 0.13.
```js
logLevel: {
	"TX": "info",
	"**": "debug"
}
```

**Comment by WoLfulus** [comment] 2018-08-04 19:16
Is this already implemented? Maybe I missed how complex this PR is. I only changed `debug` to `trace` on logger calls. This breaks environment variable settings right? (configuring "**" inside LogLevel)

**Comment by faeron** [comment] 2018-08-29 21:15
As far as I found, using trace always prints the whole stacktrace of the logged message (by design). So using log-level ``trace``seems a bad option. Also using ``debug``would just let it be as is.
Of course we could add some more log levels so there is a broader range to choose from. But that feels somehow unnecessary.

Therefore my suggestion for would be to add a setting for transit, that disables logging of packets by type. So something like:
```js
transit: {
 packetLogFilter:['HEARTBEAT']
}
```

Also all other [packet-types](https://github.com/moleculerjs/moleculer/blob/master/src/packets.js#L10-L23) that are supported by transit could then be disabled (if wanted) by just adding them.

**Closed** 2018-12-27 11:20 UTC
Labels: Type: Enhancement
