### ISSUE TITLE
Enable zero-configuration/decentralized networking like 'Cote'

### ISSUE THREAD

**Issue by demetriusnunes** [moleculerjs/moleculer#46] opened 2017-06-13 14:14 UTC
It's a pretty big win if moleculer could also work like this:
http://cote.js.org/#multicast-address

The single point of failture like NATS would be gone.

**Comment by icebob** [comment] 2017-06-13 14:36
Thanks, I will check it. I think it can be an other official transporter module.

**Comment by ivokoko** [comment] 2017-07-05 05:44
NATs could be configured as cluster, so there won't be a single point of failure

**Comment by thelinuxlich** [comment] 2017-07-06 18:20
The problem is, where will we find multicast enabled architecture? Docker for example doesn't support it.

**Comment by icebob** [comment] 2017-10-14 20:24
I'm working on a TCP+UDP transporter. It uses UDP broadcast messages to detect other Moleculer nodes on the network. If it find them, it connects to the remote nodes via TCP.

**Comment by tinchoz49** [comment] 2017-10-27 16:00
maybe this library can be helpful for the service discovery https://github.com/maxogden/discovery-channel

**Comment by deividasjackus** [comment] 2017-10-27 17:57
Or perhaps https://github.com/mafintosh/discovery-swarm that is built on top of `discovery-channel` could be of use?

**Comment by icebob** [comment] 2017-10-27 17:58
Yes, I'm checking discovery-swarm. I'm trying to create a transporter based on it.

**Comment by deividasjackus** [comment] 2017-10-27 17:59
Cote itself (as referenced in the original issue) uses https://github.com/wankdanker/node-discover btw.

**Comment by icebob** [comment] 2017-10-27 21:10
I'm testing the low-level components ([utp-native](https://github.com/mafintosh/utp-native), [peer-network](https://github.com/mafintosh/peer-network)) of discovery-swarm and it seems it is not too stable :confused: 
I.e.: if the server shutdown & restart, the clients don't find it again and throw errors.

But I will still play with them.

**Comment by WoLfulus** [comment] 2017-10-27 21:43
what about [nssocket](https://github.com/foreverjs/nssocket) ?

**Comment by tinchoz49** [comment] 2017-10-28 15:34
wow, moleculer is getting better each day, this is going to be an awesome feature. 
For the communication, this library can be helpful: https://github.com/nickdesaulniers/node-nanomsg

**Comment by TomKaltz** [comment] 2018-01-13 01:43
+1

**Comment by icebob** [comment] 2018-02-03 16:02
It is in progress. It will be a "zero configuration" TCP transporter with Gossip internode protocol (similar Cassandra gossip protocol) to detect live/offline nodes & services **without** every node connects to every other node. So it will able to handle 100+ nodes as well.
Plus a UDP auto-discovery of course. 

It will be released in the next 0.12 release in 1-2 weeks.

Branch: https://github.com/ice-services/moleculer/tree/gossip-transporter

> Gossip is a peer-to-peer communication protocol in which nodes periodically exchange state information about themselves and about other nodes they know about. The gossip process runs every second and exchanges state messages with up to three other nodes in the cluster. The nodes exchange information about themselves and about the other nodes that they have gossiped about, so all nodes quickly learn about all other nodes in the cluster. A gossip message has a timestamp associated with it so that during a gossip exchange, older information is overwritten with the most current state for a particular node.

**Comment by tinchoz49** [comment] 2018-02-03 19:57
That's really awesome @icebob! Are you planning to make this transport as the default one? 
I think it can be a good point to start with moleculer and scale your nodes, without having to worry about running a NATS server for example.

**Comment by icebob** [comment] 2018-02-03 20:16
@tinchoz49: yes. It is my plan. It will be the default transporter. So no need any transporter config, just start the nodes and everything is working :)

I'm doing performance tests. It will be the fastest transporter with ~80k req/sec on my i7. Others 10k-20k req/sec

**Comment by TomKaltz** [comment] 2018-02-03 20:32
Does broadcast messaging work via gossip or does the sending node connect
to all nodes to send the broadcast?

**Comment by icebob** [comment] 2018-02-03 20:41
No broadcast messages. INFO and HEARTBEAT are transferred with gossips. The REQUEST, RESPONSE, EVENT messages are sent to the target node directly.

**Comment by icebob** [comment] 2018-02-03 20:43
But of course you can send broadcast events with `broker.broadcast`. But they are also sent directly.

**Comment by icebob** [comment] 2018-02-05 15:07
> Gossip protocol in action in TCP transporter: https://www.youtube.com/watch?v=9yJ_Lfw-JCs

**Comment by TomKaltz** [comment] 2018-02-05 15:18
!!!!!!!!!!!

**Comment by icebob** [comment] 2018-02-05 15:19
??

**Comment by TomKaltz** [comment] 2018-02-05 15:21
I couldn’t contain my excitement. This is tremendous work @icebob

**Comment by icebob** [comment] 2018-02-05 15:25
Ohh thanks :+1: . This transporter with gossip easily can handle 100+ nodes as well. _I hope because I could test only on localhost_

**Comment by tinchoz49** [comment] 2018-02-05 15:34
niceeee! At the end of my presentation, I said, "the future is decentralized and Moleculer too". Of course a was talking about this amazing feature!

**Comment by icebob** [comment] 2018-02-05 15:36
;)

**Comment by ntgussoni** [comment] 2018-02-05 15:54
Awesome work!

**Comment by brad-decker** [comment] 2018-02-05 16:05
@icebob you never cease to amaze me :heart:

**Comment by giang12** [comment] 2018-02-16 02:38
![image](https://user-images.githubusercontent.com/5290460/36291382-632727f0-127f-11e8-83c9-e56ab5625ba7.png)

**Comment by icebob** [comment] 2018-03-03 15:38
Released in 0.12 as `TCP` transporter. [More info](https://moleculer.services/0.12/docs/transporters.html#TCP-transporter)

**Closed by icebob** 2018-03-03 15:38 UTC
Labels: Module: Transporter, Priority: Low, Status: In Progress, Type: Enhancement

**Comment by Wallacy** [comment] 2018-04-23 15:40
I did some tests in this feature... My two cents is:

udpBroadcast should be default at "255.255.255.255" because multicast enabled network is not that common, and "255.255.255.255" its a better choice for a default address to avoid manual config on every sample/example to run in some machines (same problem for multicast).

Besides that, my impression is the overall performance for this solution is not good at all (for now). The gossip protocol is interesting but have a unpredictable nature. Almost 28 seconds for 50 nodes is a eternity! I use 5-10s for connection timeout on my microservices for comparison. Compared to Cote, for exemple, i can interconnect 50 nodes in 1.2 seconds (or less).

This gossip implementation is very nice for a TCP communication protocol to enable serverless environments, but as TCP service discovery protocol needs a more direct approach i think.

**Comment by icebob** [comment] 2018-04-23 17:29
With "255.255.255.255" broadcast address has [problem](https://www.google.hu/search?ei=XhPeWsXEJ6r36ASlhoiwAQ&q=udp+broadcast+255.255.255.255+problem&oq=udp+broadcast+255.255.255.255+problem&gs_l=psy-ab.3..33i21k1l2.12897.14452.0.14650.10.10.0.0.0.0.240.959.0j4j2.6.0....0...1c.1.64.psy-ab..4.4.692....0.LweeUzEI1tk) with routers. By default, TCP transporter detects all network interfaces and send broadcasts on all interfaces and it works well. But if you need, you can use 255.255.255.255 as broadcast address in transporter config:
```
udpBroadcast: "255.255.255.255"
```

TCP transporter has the best performance at service communication thanks to the direct connection. Yes, the first discovery time can be big if you have many nodes. But my question, which is more likely? 
1. you start & stop 50 nodes in every minutes and you have to wait 28 seconds.
2. you start 50 nodes once a month and your services communicate continuously & quickly. 

If you belong to the first group, I suggest that you should use Cote, or any other transporter (NATS, Redis...etc)

**Comment by Wallacy** [comment] 2018-04-24 15:50
Okay, I did not get a chance to look at the code more closely yesterday. (I just run the examples)
Now I believe I understand what is happening.

You actually now (in less than a second) all other nodes. But actually you first add that node as Offline Node, probably to avoid get a cached upd info right?

Usually on UDP discovery you first assume that server is actually running and only put the node on offline state after not receive another information after some time (like the heartbeat), and/or after a broken pipe after try a communication via TCP.

This and other extra care is what's causing slowness.

Can i try a PR to address this? 

Also, i found the problem with the default udpBroadcast=true approach -> getBroadcastAddresses()  raises "ipaddr: the address does not have IPv4 CIDR format". That why i need one manually.

But before i make any change, can you explain a little about this (nice) design:
- Why udpMulticast as default instead udpBroadcast?
- The idea of the Gossip protocol is to overcome the unpredictable nature of the UDP and then make a TCP call to ensure the connection state and make earlier update on target node list?
- Gossip is also to overcome multiple networks interfaces?
- What do you think about a UDP heartbeat?
