### ISSUE TITLE
Hot-Reload not working without Runner

### ISSUE THREAD

**Issue by flaviocordova** [moleculerjs/moleculer#580] opened 2019-08-06 01:36 UTC
Hot Reloading is not working for services loaded with broker.loadService('path')

Take this very example:

**mod.js**
````js
module.exports = {
  name: 'myModule',

  actions: {
    hello(ctx) {
      console.log('ctx.meta:', ctx.meta)
    }
  }
}
````

**loader.js**
````js
const { ServiceBroker } = require("moleculer");
opts = {
  hotReload: true,
  logLevel: 'debug'
}
const broker = new ServiceBroker(opts)
broker.loadService('./mod')
broker.start()

const express = require('express')
const app = express()
var server = require('http').createServer(app)
server.listen(8981)
````

Module won't be reloaded when mod.js is changed.

**Comment by AndreMaz** [comment] 2019-08-10 13:45
Ok, I think I found the issue. It's in the [`processModule`](https://github.com/moleculerjs/moleculer/blob/c6cd98dfc374c02c51d840d57bba47a8ac9b9427/src/middlewares/hot-reload.js#L163) method.

Running the code as is will result in 0 files being watched. This is caused by:
https://github.com/moleculerjs/moleculer/blob/c6cd98dfc374c02c51d840d57bba47a8ac9b9427/src/middlewares/hot-reload.js#L49
and this condition
https://github.com/moleculerjs/moleculer/blob/c6cd98dfc374c02c51d840d57bba47a8ac9b9427/src/middlewares/hot-reload.js#L170-L172
that causes the `processModule` to exit straight away. 

Additionally, in `loader.js` direct children are:
- `node_modules/moleculer/index.js`
- `node_modules/express/index.js`

So the `mod.js` is never processed. To get things working had to do some changes (https://github.com/AndreMaz/moleculer/commit/b09031f18d437227b2d5d42e11b12a9234f83990).
After the changes I have the following result:
![image](https://user-images.githubusercontent.com/9802754/62822528-d11a2080-bb7c-11e9-9c03-43b47ef1a203.png)
@flaviocordova can you test it (`npm i --save github:AndreMaz/moleculer#next`) and see if it works properly?

**Comment by icebob** [comment] 2019-08-12 10:05
@AndreMaz and this commit works with moleculer-runner, as well?

**Comment by AndreMaz** [comment] 2019-08-12 14:13
Yes, I've tested on [moleculer-demo](https://moleculer.services/docs/0.13/usage.html#Create-a-Moleculer-project) with an additional `require` of `hook.js` an got the following result:
![image](https://user-images.githubusercontent.com/9802754/62858475-56731180-bcf2-11e9-9c27-51c6c0d32622.png)

**Comment by icebob** [comment] 2019-08-13 13:20
Thanks @AndreMaz & @flaviocordova the help. It's fixed and will be released in the next version.

**Closed by icebob** 2019-08-13 13:20 UTC
Labels: Module: Middleware, Type: Bug

**Comment by ujwal-setlur** [comment] 2019-12-10 20:51
Has this been released on npm yet? Is this included in 0.14-beta6? Would love to have this bug fix released.

**Comment by icebob** [comment] 2019-12-10 21:07
Yes, it's been released.

**Comment by ujwal-setlur** [comment] 2019-12-10 21:19
Hmm, it's still not working for me...works with moleculer-runner, but now when I manually create a service broker and create a service. I will test with the example code above. Also, I don't see all of @AndreMaz's fixes in the beta-6 release

**Comment by ujwal-setlur** [comment] 2019-12-10 21:29
Hmm, example code works. Need to dig more. I am using Typescript by the way, if it makes a difference...

**Comment by ujwal-setlur** [comment] 2019-12-10 21:33
when I run in debug mode, I see:

```
[2019-12-10T21:33:04.766Z] DEBUG api-3cc9e9871664/BROKER: Watching the following project files:
[2019-12-10T21:33:04.767Z] DEBUG api-3cc9e9871664/BROKER:   No files.
```

**Comment by ujwal-setlur** [comment] 2019-12-10 23:39
Turns out the following does NOT work:

```js
const ApiService: ServiceSchema = {
  name: 'api'
};

// Create our service
moleculerBroker.createService('ApiService');
```

But if create an ```api.module.ts```:

```js
module.exports = {
  name: 'api'
};
```

and then do
```js
moleculerBroker.loadService(path.join(__dirname, './api.module'));
```
then it works. So the service has to be defined as a ```module.export``` and loaded for hot-reload to work? What about files outside of the service definition file? Will those files not be watched?
