### ISSUE TITLE
Ctx is undefined when using shard strategy and preferLocal is false, throws error on emit

### ISSUE THREAD

**Issue by jscottsf** [moleculerjs/moleculer#1072] opened 2022-03-29 00:51 UTC
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

## Current Behavior

Balanced events via broker.emit with two nodes, shard strategy, and preferLocal false throws the error `Cannot read property 'params' of undefined`. Basically, the line `return _.get(ctx.params, this.opts.shardKey);` in the shard strategy function `getKeyFromContext` throws an error since the context is undefined and `params` cannot be accessed.

## Expected Behavior

A balanced event that is not-local should work. This can be fixed by:

1. Modify `getBalancedEndpoints` in event-catalog to accept `ctx` as the last argument.
2. Modify `getBalancedEndpoints` to pass the context in the `next` call, e.g. `const ep = list.next(ctx);`
3. In the `emit` function in service-broker, pass the built context as shown `getBalancedEndpoints(eventName, opts.groups, ctx);`

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Set preferLocal to false to ensure the balancer is used.
2. Enable the shard strategy which REQUIRES the context in order to access the shard key values.
3. Run two node instances.
4. Call broker.emit.

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculer version: 0.14.19
* NodeJS version: 14.17
* Operating System: Mac

**Comment by icebob** [comment] 2022-04-01 16:17
Yeah, please create a fix PR.

**Comment by intech** [comment] 2022-05-07 07:20
@jscottsf, please, check the error in my fork [`intech/moleculer`](https://github.com/intech/moleculer)

**Comment by jscottsf** [comment] 2022-05-07 21:08
Sorry that I didn't get to the PR yet. It's been on my list.

@intech Did a quick code review on the fork and it looks right. Noticed that emit became async and got some refactoring. Will this get pulled into the original repo? :)

**Comment by intech** [comment] 2022-05-07 23:04
@jscottsf It will but not now. The first is to deal with the performance slow due to refactoring.

**Comment by intech** [comment] 2022-05-29 13:05
@jscottsf сan I close this issue as resolved? I was not able to reproduce the problem during the tests.

**Comment by jscottsf** [comment] 2022-05-29 17:51
@intech Seems the code was patched in your fork. This will get merged into the main codebase I presume. If so, then yes please close. I can test in a scaled environment as well. Thank you!

**Comment by intech** [comment] 2022-05-29 17:56
@jscottsf Already merged into the master branch. Can you test from master? I want to make sure it doesn't reproduce again.

**Comment by jscottsf** [comment] 2022-05-29 19:26
I set up two runner instances with preferLocal false and NATS running. Posted to an api endpoint on one of the instances. The endpoint does an emit to trigger balanced events.

For the current production release -- round robin worked as expected. When I enabled the shard strategy with a shardKey, the issue persisted. THIS WAS EXPECTED.

Installed the version on master -- round robin worked as expected. When I enabled the shard strategy with a shardKey, IT WORKED!!!!! I tried different values in my payload to see if the request would route consistently and IT WORKED!!! (my shard key was a key in the payload I passed in)

Thank you so much!!!

**Comment by intech** [comment] 2022-05-29 19:47
@jscottsf Excellent! Thank you too for your help!

**Closed** 2022-05-29 19:47 UTC

**Comment by jscottsf** [comment] 2022-10-11 07:37
I was informed that another beach was going to fix it. It’s actually an issue since the current code does not pass the context. 

Did you fire up separate runner instances and use the NATS transporter. Over local transport it won’t happen. The tests likely don’t cover this.

**Comment by icebob** [comment] 2022-10-12 16:58
Could you create a repro test?
