### ISSUE TITLE
[discussion] Should all brokers respond to circuit breaker from one broker?

### ISSUE THREAD

**Issue by TomKaltz** [moleculerjs/moleculer#179] opened 2018-01-18 21:08 UTC
My understanding of the current circuit breaker is that the sending broker will open it's circuit to a certain node when it passes a certain error threshold.  Should the other brokers in a network respond to a global event and also open their circuits to that same node or should each broker be responsible for trying to connect to that node and opening their circuits on fault?

**Comment by icebob** [comment] 2018-03-06 11:10
First of all, currently the CB is applied to service actions and not for the node. It means that you get errors from `posts.create` action and CB opened, you can call other actions and other services on the same node.

When a CB opened, the broker emits a `$circuit-breaker.open` event for local services and emit a `metrics.circuit-breaker.open` event for monitoring & metrics services. _There is similar events for CB closing as well._

If we want to send these messages to all nodes, it can generate a lot of events, can't it? So it would be to implement as an optional feature. I plan to improve CB functions #80 in 0.13, so maybe I can implement it too.

**Comment by parveshh** [comment] 2018-03-23 12:42
i am not able to trigger circuit breaker, could someone check the code below and point out the obvious mistake:

```javascript
const { ServiceBroker } = require("moleculer");


const broker = new ServiceBroker({
    logger: console,
    circuitBreaker: {
        enabled: true,
        maxFailures: 2,
        failureOnReject: true,
        failureOnTimeout: true
    },
    transporter: {
        type: "NATS",
        options: {
            urls: [
                "nats://localhost:14222",
                "nats://localhost:24222",
                "nats://localhost:34222"

            ],
        }
    }
});


broker.createService({


    name: "message",
    events: {
        //this is not getting triggered on calling message.print service
        "$circuit-breaker.open"(payload) {
           console.log(payload);
          broker.broadcast("circuit.open", payload);
        }
    },

    actions: {
        print(ctx) {
            console.log("message.print");
         //tried with Promise.reject as well
            throw new Error("could not print message");


        }
    }
});

broker.start();
```

i have 2nd service which uses moleculer-web to call message.print

```javascript
const { ServiceBroker } = require("moleculer");
const ApiService = require("moleculer-web");

let broker = new ServiceBroker({
    circuitBreaker: {
        enabled: true,

        maxFailures: 2

    },
    nodeID: "gate",
    cacher: "memory",
    logger: console,
    transporter:  {
        type: "NATS",
        options: {
            urls: [
                "nats://localhost:14222",
                "nats://localhost:24222",
                "nats://localhost:34222"
                        
            ],
        }
    }
});


broker.createService({
    mixins:[ApiService],
    settings: {
        
        routes: [{
            path:"/api",
            aliases: {
                
                "GET message/:messageId":"message.print"
               
            }
        }]
    },
    name: "test",

});

broker.start();
```

**Comment by icebob** [comment] 2018-03-23 14:31
@parveshh Your code is correct. The problem is on documentation side. The correct event name is `$circuit-breaker.opened`. Sorry, I will fix it in the docs.

**Comment by parveshh** [comment] 2018-03-23 14:47
great thanks @icebob  i will try now

**Closed** 2023-01-14 13:18 UTC
Labels: Priority: Low, Status: Proposal, Type: Enhancement, Module: Core
